
SITE_TITLE			:= FlatPress
SITE_TAG			:= Textos aleatorios e irrelevantes
TEMPLATE			:= $(SITE_CONTENTS_DIR)/resources/template.html
INDEX_TEMPLATE		:= $(SITE_CONTENTS_DIR)/resources/index-template.html
INCLUDE_IN_HEADER	:= $(SITE_CONTENTS_DIR)/resources/head-links.html
